# Generated by Django 3.2.8 on 2021-10-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='idProduct',
            new_name='id',
        ),
    ]
