# Generated by Django 3.2.8 on 2021-10-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_rename_idproduct_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='idInvoice',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='idSale',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paymentMethod',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost'),
        ),
    ]
